[package]
name = "itoap"
version = "0.1.0"
authors = ["Ryohei Machida <orcinus4627@gmail.com>"]
description = "Even faster functions for printing integers with decimal format"
homepage = "https://github.com/Kogia-sima/itoap"
repository = "https://github.com/Kogia-sima/itoap"
readme = "README.md"
categories = ["value-formatting"]
license = "MIT"
edition = "2018"

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[dev-dependencies]
bencher = "0.1.5"
itoa = { version = "0.4.6", features = ["i128"] }

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
